inherit_gem:
  rubocop-discourse: stree-compat.yml

AllCops:
  Exclude:
    - gems/**/*

Style/GlobalVars:
  AllowedVariables: [$prometheus_client, $parent_pid, $port, $pid_file]

Discourse/Plugins/NamespaceMethods:
  Exclude:
    - bin/**/*
