inherit_gem:
  rubocop-discourse: stree-compat.yml

Style/GlobalVars:
  AllowedVariables: [$prometheus_client, $parent_pid, $port, $pid_file]

Plugins/Discourse/NamespaceMethods:
  Exclude:
    - bin/**/*
